export default [
  {
    id: '1808500',
    steam: {
      id: '1808500',
      name: 'ARC Raiders',
      price: '39,99€',
      url: 'https://store.steampowered.com/app/1808500',
      developers: [null],
      publishers: [null],
      releaseDate: '2025-10-30',
    },
    epic: {
      id: '1808500',
      name: 'ARC Raiders',
      price: '39,99€',
      url: 'https://store.epicgames.com/en-US/p/arc-raiders',
      developers: [null],
      publishers: [null],
      releaseDate: '2025-10-30',
    },
  },
  {
    id: '2767030',
    steam: {
      id: '2767030',
      name: 'Marvel Rivals',
      price: 'Free',
      url: 'https://store.steampowered.com/app/2767030',
      developers: [null],
      publishers: [null],
      releaseDate: '2024-12-05',
    },
    epic: {
      id: '2767030',
      name: 'Marvel Rivals',
      price: 'Free',
      url: ' https://store.epicgames.com/en-US/p/marvel-rivals-182004',
      developers: [null],
      publishers: [null],
      releaseDate: '2024-12-05',
    },
  },
  {
    id: '2807960',
    steam: {
      id: '2807960',
      name: 'Battlefield™ 6',
      price: '69,99€',
      url: 'https://store.steampowered.com/app/2807960',
      developers: [null],
      publishers: [null],
      releaseDate: '2025-10-10',
    },
    epic: {
      id: '2807960',
      name: 'Battlefield™ 6',
      price: '69,99€',
      url: 'https://store.epicgames.com/en-US/p/battlefield-6',
      developers: [null],
      publishers: [null],
      releaseDate: '2025-10-10',
    },
  },
  {
    id: '489830',
    steam: {
      id: '489830',
      name: 'The Elder Scrolls V: Skyrim Special Edition',
      price: '39,99€',
      url: 'https://store.steampowered.com/app/489830',
      developers: [null],
      publishers: [null],
      releaseDate: '2016-10-27',
    },
    epic: {
      id: '489830',
      name: 'The Elder Scrolls V: Skyrim Special Edition',
      price: '9,99€',
      url: 'https://store.epicgames.com/en-US/p/skyrim',
      developers: [null],
      publishers: [null],
      releaseDate: '2016-10-27',
    },
  },
  {
    id: '850190',
    steam: {
      id: '850190',
      name: 'Goat Simulator 3',
      price: '11,99€',
      url: 'https://store.steampowered.com/app/850190',
      developers: [null],
      publishers: [null],
      releaseDate: '2024-02-15',
    },
    epic: {
      id: '850190',
      name: 'Goat Simulator 3',
      price: '11,99€',
      url: 'https://store.epicgames.com/en-US/p/goat-simulator-3',
      developers: [null],
      publishers: [null],
      releaseDate: '2024-02-15',
    },
  },
];
